<?php

namespace melon\RefappBundle\Controller;

/**
 * This code has been auto-generated by the JMSDiExtraBundle.
 *
 * Manual changes to it will be lost.
 */
class FavorisController__JMSInjector
{
    public static function inject($container) {
        require_once '/home/romain/mairie2013-2014/Symfony/app/cache/prod/jms_diextra/proxies/melon-RefappBundle-Controller-FavorisController.php';
        $d = new \JMS\AopBundle\Aop\InterceptorLoader($container, array('melon\\RefappBundle\\Controller\\FavorisController' => array('favorisAction' => array(0 => 'security.access.method_interceptor'))));
        $instance = new \EnhancedProxy_1f161ba14b50e379e418b1f1186c013bbebe1bee\__CG__\melon\RefappBundle\Controller\FavorisController();
        $instance->__CGInterception__setLoader($d);
        return $instance;
    }
}
