<?php

namespace melon\RefappBundle\Controller;

/**
 * This code has been auto-generated by the JMSDiExtraBundle.
 *
 * Manual changes to it will be lost.
 */
class IndexController__JMSInjector
{
    public static function inject($container) {
        require_once '/home/romain/mairie2013-2014/Symfony/app/cache/prod/jms_diextra/proxies/melon-RefappBundle-Controller-IndexController.php';
        $a = new \JMS\AopBundle\Aop\InterceptorLoader($container, array('melon\\RefappBundle\\Controller\\IndexController' => array('indexAction' => array(0 => 'security.access.method_interceptor'))));
        $instance = new \EnhancedProxy_140cf90b257a262675fc4a4f52821f1e4ccd19c4\__CG__\melon\RefappBundle\Controller\IndexController();
        $instance->__CGInterception__setLoader($a);
        return $instance;
    }
}
