<?php

namespace melon\RefappBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * DirectionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DirectionRepository extends EntityRepository
{	
	public function search($data)
	{

		$qb = $this->createQueryBuilder('d')
		->leftJoin('d.applications', 'a')
		->addSelect()
		->where('d.nom = :nom')
		->setParameter('nom', $data);
	
		return $qb->getQuery()
		->getResult();
	}
}
