<?php

namespace melon\RefappBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * DomaineRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DomaineRepository extends EntityRepository
{
	
public function search($data)
	{		
		
		/*$qb->select('d')
		->from('melonRefappBundle:Application', 'a')
		->where('d.nom = :nom')
		->setParameter('nom', $data["domaine"]);*/
		
		$qb = $this->createQueryBuilder('d')
		->leftJoin('d.applications', 'a')
		->addSelect()
		->where('d.nom = :nom')
		->setParameter('nom', $data);
		
		
		/*$qb = $this->createQueryBuilder('d')
			->where('d.nom = :nom')
			->setParameter('nom', $data["domaine"]);
		
		
		/*$qb->createQuery('
            SELECT a, c FROM melonRefappBundle:Application a
            JOIN p.category c
            WHERE p.id = :id'
        );*/
		
		return $qb->getQuery()
				->getResult();
	}
}
