<?php

namespace melon\RefappBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * rechercheAppliRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RechercheAppliRepository extends EntityRepository
{
	
	public function search($data)
	{	
		$qb = $this->_em->createQueryBuilder();
		
		$qbDomaine =$this->getDoctrine()
						 ->getManager()
						 ->getRepository('melonRefappBundle:Domaine')
						 ->search($data["domaine"]);
		
		$qbDirection =$this->getDoctrine()
						 ->getManager()
						 ->getRepository('melonRefappBundle:Direction')
						 ->search($data["direction"]);
		

		
		$qb = $this->createQueryBuilder('')
		->leftJoin('a.domaine', 'd')
		->addSelect('d')
		->where('d.nom = :nom')
		->setParameter('nom', $data["domaine"]);
	
		return $qb->getQuery()
		->execute();	
	}
	
	
}
