<?php

namespace melon\RefappBundle\Controller;

/**
 * This code has been auto-generated by the JMSDiExtraBundle.
 *
 * Manual changes to it will be lost.
 */
class ApplicationController__JMSInjector
{
    public static function inject($container) {
        require_once '/home/romain/mairie2013-2014/Symfony/app/cache/dev/jms_diextra/proxies/melon-RefappBundle-Controller-ApplicationController.php';
        $a = new \JMS\AopBundle\Aop\InterceptorLoader($container, array('melon\\RefappBundle\\Controller\\ApplicationController' => array('ficheAppliAction' => array(0 => 'security.access.method_interceptor'), 'listeAppliAction' => array(0 => 'security.access.method_interceptor'), 'rapportObsolescenceAction' => array(0 => 'security.access.method_interceptor'), 'pdfAction' => array(0 => 'security.access.method_interceptor'), 'creerAppliAction' => array(0 => 'security.access.method_interceptor'), 'mesAppliAction' => array(0 => 'security.access.method_interceptor'), 'rechercheAppliAction' => array(0 => 'security.access.method_interceptor'), 'nouvelEditeurAction' => array(0 => 'security.access.method_interceptor'), 'modifierAppliAction' => array(0 => 'security.access.method_interceptor'), 'supprimerAppliAction' => array(0 => 'security.access.method_interceptor'))));
        $instance = new \EnhancedProxy_71bd0ae24ff9b417f4efe31750fc6da78b749933\__CG__\melon\RefappBundle\Controller\ApplicationController();
        $instance->__CGInterception__setLoader($a);
        return $instance;
    }
}
