<?php

namespace Ps\PdfBundle\Controller;

/**
 * This code has been auto-generated by the JMSDiExtraBundle.
 *
 * Manual changes to it will be lost.
 */
class ExampleController__JMSInjector
{
    public static function inject($container) {
        $instance = new \Ps\PdfBundle\Controller\ExampleController();
        return $instance;
    }
}
